### PR TITLE
textsplitter: add markdown header text splitter

### PR DESCRIPTION
**Pull request by edocevol**
For issue: #273 

### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [x] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Comment by sssvip** [comment]
Good job!

**Comment by tmc** [comment]
Can you include rationale for this library vs Goldmark?

**Comment by edocevol** [comment]
> Can you include rationale for this library vs Goldmark?

In my previous work experience, I used golang-commonmark, and I will check if Goldmark can be used as a replacement.

**Comment by edocevol** [comment]
> Can you include rationale for this library vs Goldmark?

I have made some attempts. Goldmark uses a "tree" data structure to represent the nodes of Markdown, while golang-commonmark/markdown uses an array, and each node is delimited by Open and Close tags. Both libraries can be used, but migrating to Goldmark requires a lot of effort.

**Review by tmc — APPROVED** [review]
Feels like we should introduce an interface here and not take on the new direct dependency (we need to do more of that throughout)

**Pull request merged**
