### PR TITLE
embeddings: remove unnecessary mostly-duplicated implementations

### PR DESCRIPTION
**Pull request by eliben**
### PR Checklist

- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [x] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Review by tmc — APPROVED** [review]
Thanks @eliben! Much cleaner.

**Comment by eliben** [comment]
They're only removed from the `embeddings` directory.

Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of what you're trying to accomplish?

**Comment by eliben** [comment]
Sorry, I'm still having trouble understanding what you're trying to accomplish. The code that was removed duplicated all the embeddings implementation with the only difference being that it forwarded the `CreateEmbedding` method to the underlying client. This design didn't make a lot of sense, but it also wasn't clear what the goal is.

Can you provide an example of the actual problem you're trying to solve? Do you have a `llm.Chat` but not the underlying `llm.Client` and you're trying to get embeddings from it? How does this situation arise? Can you get embeddings from the client, not the chat? I'm confused about the duplication here.

**Comment by eliben** [comment]
BTW, I recommend opening a new issue to discuss this - for more visibility. Feel free to @ me if you want to create one and provide an example

**Comment by zivkovicn** [comment]
@eliben opened the issue, if you like you can find me on the discord as well to chat about this or even hop on the call if needed.

**Pull request merged**
