### PR TITLE
Update split_documents.go

### PR DESCRIPTION
**Pull request by ujjwall-R**

### CODE REVIEW

**Comment by tmc** [comment]
@ujjwall-R can you fix this PR? it has no description and linting is failing

**Comment by ujjwall-R** [comment]
Have you tried using the split text?
I corrected it locally then its working.

**Comment by FluffyKebab** [comment]
@ujjwall-R can you give the code you where you tried to split the text?

**Comment by tmc** [comment]
@ujjwall-R I'm going to close this due to inactivity but feel free to re-open.

**Pull request closed without merging**
