### PR TITLE
llms: Perplexity.ai support proposal

### PR DESCRIPTION
**Pull request by devalexandre**
### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [ ] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [ ] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Comment by tmc** [comment]
Looking forward to this!

**Comment by devalexandre** [comment]
@tmc :)

**Comment by tmc** [comment]
Does this need to differ from the OpenAI backend?

**Comment by devalexandre** [comment]
> Does this need to differ from the OpenAI backend?

maybe a flag like azure would be better?

**Comment by devalexandre** [comment]
@tmc , I go add in openai, but have a error when use WithBaseUrl

```
error(*net/url.Error) *{Op: "Post", URL: "https://api.perplexity.com/chat/completions", Err: error(*net.OpError) *{Op: "dial", Net: "tcp", Source: net.Addr nil, Addr: net.Addr nil, Err: error(*net.DNSError) ...}}
```

I'm trying to understand why I get this error

**Comment by devalexandre** [comment]
the url was wrong LOL, implementation finished

**Pull request closed without merging**
