### PR TITLE
Feat(openaiclient): add Option for custom HTTP client

### LINKED ISSUE #90: Allows setting custom http client
Reasons for example: In many areas, the local network cannot directly access the address of openai, and proxy settings are required to access

### PR DESCRIPTION
**Pull request by obitech**
This MR adds a variadic `Option` to the OpenAI client, allowing for future customizations. It also adds the `WithHTTPClient` option that allows setting custom HTTP clients.

Closes #90 

### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Describes source of new concepts.
- [x] References existing implementations as appropriate.
- [ ] Contains test coverage for new functions.
- [ ] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.
- [ ] (remove and do not use this row unless you are a trusted contributor) I am an existing
  contributor.

### CODE REVIEW

**Comment by obitech** [comment]
@tmc you reckon this needs tests?

**Review by tmc — APPROVED** [review]
LGTM

**Comment by obitech** [comment]
@tmc I think the lint job timed out 🤔

**Review by tmc — APPROVED** [review]
LGTM

**Comment by tmc** [comment]
> @tmc I think the lint job timed out 🤔

Yeah, we had a poisoned cache so I disabled caching, I'll turn it back on.

**Comment by chengruo** [comment]
I'm new to go and  confused that why not add WithHttpClient in the ` llms/openai/openaillm_option.go` ，cause  can't  call internal package  `llms/openai/internal/openaiclient/openaiclient.go`

**Pull request merged**
