### PR TITLE
tools: web scraper

### PR DESCRIPTION
**Pull request by Struki84**
Added a simple web scraper tool, you can set the scraping depth when creating the tool, default is 1. The tool will scrap all the links it finds on the domain, will not follow outside links. Depending on the size of the website it might take a while. 

Will return a string containing all the content it found, meta data, list of links and scraped links. Will comply with robots.txt

### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [x] References existing implementations as appropriate.
- [ ] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Comment by Struki84** [comment]
@tmc @FluffyKebab any feedback on this?

**Comment by tmc** [comment]
Can you make the options configurable (not just depth).

**Comment by Struki84** [comment]
@tmc is this better?

**Comment by Struki84** [comment]
bump ^^

**Review by tmc — APPROVED** [review]
LGTM

**Pull request merged**
