### PR TITLE
llms: add watsonx

### PR DESCRIPTION
**Pull request by h0rv**
This is using https://github.com/h0rv/go-watsonx to keep the Langchain and API client development seperate (was going to add the logic in `llms/watsonx/internal/watsonxclient`).

Resolves: https://github.com/tmc/langchaingo/issues/567

### PR Checklist

- [ ] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [ ] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [ ] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [ ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [ ] Describes the source of new concepts.
- [ ] References existing implementations as appropriate.
- [ ] Contains test coverage for new functions.
- [ ] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Comment by h0rv** [comment]
I have a concern: the watsonx docs are not great yet and do not have the default generation parameter values documented. However, if you don't include them in the payload, they will be defaulted. So, in the options struct for the generation parameters, I had to use pointers (ex `*float64` for temperature), with `omitempty`, to omit it from the payload if it is not specified.

What I need to do now is convert `llms.CallOptions` to `[]wx.GenerationOption`, but it is difficult because I can check which options are not their default zero values, but for something like `Temperature`, its range is 0-1 inclusive, so I won't be able to distinguish if the user set it to 0, or if the user did not specify, and it defaulted to 0.

Any thoughts on how to approach this? Thanks!

**Comment by h0rv** [comment]
I can set the `Temperature` and similar options to `-1`, since they are not `uint`'s.

**Comment by tmc** [comment]
can you resolve the conflicts here please?

**Comment by h0rv** [comment]
How do I fix the CI that is failing? @tmc

**Comment by h0rv** [comment]
Hi @tmc, I think this is a chicken and the egg problem b/c its pulling the package in each example directory. Should I add it in a separate PR or is there a way to fix? Thanks

```
go: github.com/tmc/langchaingo/examples/watsonx-llm-example imports
	github.com/tmc/langchaingo/llms/watsonx: module github.com/tmc/langchaingo@latest found (v0.1.4), but does not contain package github.com/tmc/langchaingo/llms/watsonx
go: updates to go.mod needed; to update it:
	go mod tidy
make: *** [Makefile:53: build-examples] Error 1
```

**Comment by tmc** [comment]
A few more conflicts came up -- regarding the example -- in the short term you could include a go.work file in the examples directory and once merged I can clean up the go.work file.

I'd liek to get 0.1.6 tagged today and would love to include this!

**Comment by tmc** [comment]
I rebased this to main and pushed to your branch. Futher, I pushed this to the main repository as the `add-watsonx` branch which you could reference in your example. I don't belive these lint/build failures are a rebase snafu but please examine.

**Comment by h0rv** [comment]
@devalexandre Do you know how to help fix the CI issue?

**Comment by devalexandre** [comment]
> @devalexandre Do you know how to help fix the CI issue?

I yes , I can do PR for you branch?

**Comment by tmc** [comment]
This is pushed as `add-watsonx` so you can point your branch to that in the mean time.

**Comment by h0rv** [comment]
Great that fixed it - thanks for the help!

**Comment by h0rv** [comment]
@tmc @devalexandre Ready for a review now, thanks!

**Comment by tmc** [comment]
Thanks!

**Pull request merged**
