### PR TITLE
openaillm: Add more CallOptions to Chat and Completion Requests, add GenerationInfo to Chat response

### PR DESCRIPTION
**Pull request by mcartagenah**
Description:

Added a way of using temperature and maxtokens with a llm chain.

### PR Checklist

- [X] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [X] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [X] Name your Pull Request title clearly, concisely, and prefixed with the name of primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Describes source of new concepts.
- [x] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.
- [ ] (remove and do not use this row unless you are a trusted contributor) I am an existing
  contributor.

### CODE REVIEW

**Comment by mcartagenah** [comment]
I noticed this is implemented partially in #137 , but this options should also be added to the ChatRequest struct.

**Comment by tmc** [comment]
@mcartagenah Ah good point. can you rebase/refresh this?

**Comment by mcartagenah** [comment]
Added all the CallOptions possible to Chat and Completion for OpenAI LLM, also added the GenerationInfo that was missing from the Chat response :)

**Comment by tmc** [comment]
Hm this is showing lots of changes as compared to main, can you re-check the rebase?

**Pull request closed without merging**
