### PR TITLE
Improving HuggingfaceLLM: Configurable RepoID option

### PR DESCRIPTION
**Pull request by EvilFreelancer**
### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Describes source of new concepts.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

---

Phew, your questionnaire is quite complex, feels like I'm taking exams :)

Here's a brief description of this PR. It allows the use of HuggingFace pipelines by specifying a custom repository instead of hardcoded "google/flan-t5-xl" (which not work btw). For my tests, I used the GPT-2 model, but any other model can be used if desired.

I implemented the mentioned setting through `llms.WithModel` and demonstrated its usage in the corresponding example. I'm sure this will help newcomers like me to understand how to use this library more quickly.

Thank you guys for this amazing extension! I've trying to integrate executing of Python scripts to LocalAI and you saved a lot of my time.

PS. Idk how to test it correctly, al lot of existing tests don't check similar thing, so maybe you may help me with it.

### CODE REVIEW

**Review by tmc — APPROVED** [review]
Thanks, that was nagging me, LGTM.

**Comment by tmc** [comment]
"Phew, your questionnaire is quite complex, feels like I'm taking exams :)" -- you're right that this is probably too onerous -- can you open a PR to shorten this checklist to the essentials?

**Comment by tmc** [comment]
@EvilFreelancer After thinking a bit more -> why can't we use/re-use the WIthModel option for this?

**Comment by EvilFreelancer** [comment]
> "Phew, your questionnaire is quite complex, feels like I'm taking exams :)" -- you're right that this is probably too onerous -- can you open a PR to shorten this checklist to the essentials?

Hi! You mean just update the description or recreate PR from scratch? (close this and create another one)

**Comment by EvilFreelancer** [comment]
> @EvilFreelancer After thinking a bit more -> why can't we use/re-use the WIthModel option for this?

I've just noticed this function, didnt saw it earlier, but yeah, why not :) ill change to it then

**Comment by EvilFreelancer** [comment]
Now it looks better, thanks for the tip!

**Review by tmc — APPROVED** [review]
this will probably blow up if opts.model is empty -- I can accept this but do you think we should have a default?

**Comment by EvilFreelancer** [comment]
> this will probably blow up if opts.model is empty -- I can accept this but do you think we should have a default?

It's a good idea, but id model will be an empty user will see an error about this,

**Pull request merged**
