### PR TITLE
vectorstore: openai apikey is must required only when embedder is nil

### PR DESCRIPTION
**Pull request by bjwswang**
### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [x] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Comment by bjwswang** [comment]
@tmc @noodnik2  This pr contains a few changes:
1. make openai apikey must required only when embedder is nil.
2. collection name is duplicated with namespace. we keep namespace .
3.

**Review by tmc — COMMENTED** [review]
I think this is a positive change -- Can you explain removing the collection name option?

**Comment by bjwswang** [comment]
> I think this is a positive change -- Can you explain removing the collection name option

collection name is the concept in chroma which is the same thing as namespace

**Comment by bjwswang** [comment]
> > I think this is a positive change -- Can you explain removing the collection name option
> 
> collection name is the concept in chroma which is the same thing as namespace

either we use collection or namespace

**Comment by noodnik2** [comment]
> > I think this is a positive change -- Can you explain removing the collection name option
> 
> collection name is the concept in chroma which is the same thing as namespace

I originally kept namespace separate from collection because I thought it was useful.  Previously, all items in the same collection were kept separate between namespaces using a filter on the query.  That is - a "collection" is like a database which can store elements logically separated into separate namespaces, enforced through (filter) predicates. 

If that's not useful, then I have no concerns about removing support for this distinction.

**Review by noodnik2 — COMMENTED** [review]
Apologies for the late review.  Work's been keeping me busy!

Consider removing the `getNamespacedFilter` and everything related to it.  Now that namespaces are just collections, there's no need for this filter, which previously was used to separate objects in the same collection but different namespaces. 
 
Presuming the ability to support namespaces within collections is not important, this change looks good.  I do suggest removing all vestiges of that support, now that it's not needed (describe in previous paragraph).

**Comment by noodnik2** [comment]
> > I think this is a positive change -- Can you explain removing the collection name option
> 
> collection name is the concept in chroma which is the same thing as namespace

Perhaps I'm guilty of "overengineering" if in fact support for both together (i.e., multiple namespaces within a single collection) in my initial implementation was not needed or desired.  Good catch, if so!

**Comment by noodnik2** [comment]
> btw... I don't think we should treat openai so different. Use a common embedder is good enough @noodnik2 any thought?

Not sure what you mean by "use a common embedder."  If I'm not mistaken, I had supported both the provided embedder, or the internal OpenAI embedder if one was not provided.

**Pull request merged**
