### PR TITLE
refactor: adding support for .env files in examples

### PR DESCRIPTION
**Pull request by mfreeman451**

### CODE REVIEW

**Comment by danielchalef** [comment]
@tmc Are you intending on maintaining this repo? There have been some great contributions recently, but the PRs haven't been merged. Perhaps transfer ownership to @FluffyKebab / @mfreeman451 if you don't have the bandwidth to maintain this project? I'd love to move from Python langchain to a Go implementation...

**Comment by tmc** [comment]
@mfreeman451 can you please include a title and description to aid in review here?

**Comment by tmc** [comment]
@danielchalef yes I had an issue with my notifications so I missed this PR

**Comment by tmc** [comment]
@mfreeman451 can you please rebase this?

**Pull request closed without merging**
