### PR TITLE
llms: Add fake package

### PR DESCRIPTION
**Pull request by devalexandre**
### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [ ] Describes the source of new concepts.
- [ ] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Comment by devalexandre** [comment]
> You checked " Provide a description in this PR that addresses what the PR is solving, or reference the issue that it solves (e.g. Fixes #123).", but in fact it's not clear at all what and why this is doing.
> 
> Also, the code is full of Portuguese comments and strings, is this intentional?

sorry , I'll update to en and edit the list

**Comment by flc1125** [comment]
I suggest adding a `Generate` interface to pass in, instead of `responses []string`.

Then implement a `Default Generate` to support it. This would allow for better customization and extensibility.

**Review by tmc — APPROVED** [review]
LGTM. would be cool to support streaming.

Please leave source comments in english

**Review by tmc — APPROVED** [review]
LGTM

**Pull request merged**
