### PR TITLE
vectorstores: Add support for OpenAI Organization ID header in Chroma

### PR DESCRIPTION
**Pull request by AshDevFr**
* Update `chroma-go` to the latest version (To include [this PR](https://github.com/amikos-tech/chroma-go/pull/27)
* Add error handling to NewOpenAIEmbeddingFunction
* Add a new property to the store (`openaiOrganization`) and pass it to `chroma-go`

The goal of this PR is to add support for the OpenAI Organization ID header in Chroma. It is already supported [here](https://github.com/tmc/langchaingo/blob/main/llms/openai/internal/openaiclient/openaiclient.go#L158) by the OpenAI client in Langchain but it was missing from the chroma implementation.

### PR Checklist

- [X] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [X] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [X] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [X] Describes the source of new concepts.
- [X] References existing implementations as appropriate.
- [X] Contains test coverage for new functions.
- [X] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Review by tmc — COMMENTED** [review]
can you verify this chroma release is appropriate? cc @tazarov since https://github.com/tmc/langchaingo/pull/640 just went in

**Comment by tazarov** [comment]
@tmc, I've just added a new release for Chroma-go (v.0.0.2) with the OpenAI org change that @AshDevFr , pushed a few days back - https://github.com/amikos-tech/chroma-go/releases/tag/v0.0.2

@AshDevFr, do you mind updating your `go.mod/sum`.

**Comment by AshDevFr** [comment]
Updated the version

**Comment by AshDevFr** [comment]
@tazarov I see that the `v0.0.2` does not return 2 values to `NewOpenAIEmbeddingFunction`. 

I'll update this PR soon

**Comment by AshDevFr** [comment]
It should be good to go.

**Comment by tazarov** [comment]
@AshDevFr, yeah, sorry about that. Since this was a breaking change I wanted to move it to 0.1.x tag.

**Review by tmc — COMMENTED** [review]
great! Can we make this "OpenAI" vs "OpenAi" in terms of exposed interface to be more consistent with existing code? (with that it can go in). (also needs rebase)

**Comment by AshDevFr** [comment]
Do you mean changing `WithOpenAIOrganizationID` to `WithOpenAiOrganizationID` in `chroma-go`?

**Comment by tmc** [comment]
we should be using "OpenAI" instead of "OpenAi"

**Comment by AshDevFr** [comment]
Ok I changed the whole `Chroma` interface to only use `OpenAI` instead of `OpenAi` but it will introduce a breaking change.

**Review by tmc — APPROVED** [review]
LGTM

**Pull request merged**
