### PR TITLE
docs: add docs folder and parity matrix md file

### PR DESCRIPTION
**Pull request by O-Roma**
Add a docs folder with the parity matrix md file from  #61

### CODE REVIEW

**Comment by FluffyKebab** [comment]
The matrix is wrong. I think it is just copied from the typescript version.

In text splitters we don't have:
- Character Text Splitter
- Markdown Text Splitter

In chains we only have
- llm chain
- Stuff Combine Documents Chain
- And one question answering chain

In agents, I belive we have just the zero-shot-react-description one and in memory we only have the buffer memory currently. I also think the matrix should contain information about output parsers and document loaders.

**Comment by O-Roma** [comment]
You are right @FluffyKebab . Sorry I didn't check. I got it from the issue and thought it was already checked. I updated the table with the info you provided. Now we should keep polishing it until it makes sense and it's not just a copy from the typescript version 😞

**Comment by FluffyKebab** [comment]
@O-Roma No reason to be sorry, it was completely fair to assume that the matrix from the issue was correct.

**Comment by tmc** [comment]
@O-Roma this looks ready to review, going to mark it as such.

**Review by tmc — APPROVED** [review]
Thanks! LGTM -- we'll be treating this as a living document so I'm going to go ahead an merge even if there's a thing or two to tweak.

**Pull request merged**
