### PR TITLE
llms: add caching functionality for Models

### LINKED ISSUE #395: Support  LLM Caching
https://python.langchain.com/docs/modules/model_io/llms/llm_caching

### PR DESCRIPTION
**Pull request by corani**
New caching functionality has been added to langchaingo to boost
execution speed for repetitive tasks.  Specifically, we implemented
an in-memory caching for Language Learning Models (LLMs) so that once
a model generates a content from a sequence of messages, this result
is stored in the cache. Any subsequent calls with the same sequence of
messages will read the result from the cache, instead of having the
LLM regenerate it, this optimization is intended to reduce the
response time for recurring requests.

This caching functionality is generic, different cache backends can be
used when creating the wrapper. To accomplish this, the 'llms/cache'
package was created with a generic wrapper that adds caching to a
'llms.Model'. The 'llms/cache/inmemory' package was also created for
the in-memory implementation of the cache.

Additionally, a caching example was included to demonstrate the usage
of the implemented caching mechanism.

Minor fix: Typo error in 'TotalTokesn' was corrected to 'TotalToken'
in 'ollama/ollamallm.go'.

Resolves #395

### PR Checklist

- [X] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [X] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [X] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [X] Describes the source of new concepts.
- [X] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Comment by corani** [comment]
First draft, comments are welcome!

I've included an example to demonstrate the usage, output:

```
Iteration #0

The first man to walk on the moon was Neil Armstrong. He stepped foot onto the lunar surface on July 20, 1969, during the Apollo 11 mission. Armstrong famously declared, "That's one small step for man, one giant leap for mankind," as he became the first person to walk on the moon.

(took 4.36054737s)
========================
Iteration #1

The first man to walk on the moon was Neil Armstrong. He stepped foot onto the lunar surface on July 20, 1969, during the Apollo 11 mission. Armstrong famously declared, "That's one small step for man, one giant leap for mankind," as he became the first person to walk on the moon.

(took 53.469µs)
========================
Iteration #2

The first man to walk on the moon was Neil Armstrong. He stepped foot onto the lunar surface on July 20, 1969, during the Apollo 11 mission. Armstrong famously declared, "That's one small step for man, one giant leap for mankind," as he became the first person to walk on the moon.

(took 3.977µs)
========================
```

**Comment by corani** [comment]
Todo:

- [ ] Patch streaming function

**Comment by corani** [comment]
@tmc this is ready for review

**Comment by corani** [comment]
Ping @tmc 😉

**Comment by tmc** [comment]
Looking.

**Comment by corani** [comment]
Rebased on latest main. @tmc are you still interested in taking this?

**Review by tmc — APPROVED** [review]
Lovely! Thanks for your contribution.

**Pull request merged**
