### PR TITLE
Logging concept

### PR DESCRIPTION
**Pull request by rdbell**
- Added `logger` package to give output on what the LLM is doing as an agent is running through its chain.
- Minor code cleanup/refactoring.

This replaces some basic `fmt.Println` statements and adds more verbose logging with better context and a visual system for viewing and debugging an LLM agent's process as it works through the chain of commands.

Here's what it looks like in action:

Screenshot 2023-05-03 at 1 21 43 AM

And in compact mode:

Screenshot 2023-05-03 at 1 23 32 AM

### PR Checklist

- [X] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [X] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [X] Name your Pull Request title clearly, concisely, and prefixed with the name of primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [X] Describes source of new concepts.
- [X] References existing implementations as appropriate.
- [X] Contains test coverage for new functions.
- [X] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.
- [X] I am an existing contributor.

### CODE REVIEW

**Review by tmc — COMMENTED** [review]
I like this a lot but I think we should adjust the approach a bit: expose a Logger interface on this package and a default implementation like you have and then we can implement WithLogger() style options to enable passing around /setting loggers.

Thoughts?

**Comment by bdqfork** [comment]
May be introduce callbacks instead? #108

**Comment by navicstein** [comment]
I think this is super useful

**Comment by tmc** [comment]
As we have callbacks landed (with a sample handler for logging) I thinik we can close this.

**Pull request closed without merging**
