### PR TITLE
feat: Memory Integrations (chat history)

### PR DESCRIPTION
**Pull request by nidzola**
### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [x] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

## Description
- adding the ability to port in any memory integration for the buffer
- by this logic, we can pass in any store that we would like to have to keep track of the chat history
Screenshot 2023-07-21 at 6 00 32 PM

### CODE REVIEW

**Comment by Struki84** [comment]
Very nice! As I understand this will allow me to implement a postgre based chat message history, which I attempted in https://github.com/tmc/langchaingo/pull/186

**Comment by zivkovicn** [comment]
> Very nice! As I understand this will allow me to implement a postgre based chat message history, which I attempted in #186

exactly! 😄

**Comment by Struki84** [comment]
@tmc Can we add `option.WithTokenLimit()` or something of the kind here? I know python lib has TokenBuffer class to flush to chat msgs that overflow the token size for a model. Not sure if we need an entirely new buffer for that, so we might consider it... cc @FluffyKebab 

related to https://github.com/tmc/langchaingo/issues/125

**Comment by nidzola** [comment]
> @tmc Can we add `option.WithTokenLimit()` or something of the kind here? I know python lib has TokenBuffer class to flush to chat msgs that overflow the token size for a model. Not sure if we need an entirely new buffer for that, so we might consider it... cc @FluffyKebab
> 
> related to #125

I will see when I grab time, to add the token limit, like they have in the python lib, maybe we can do it as a separate PR.

**Review by tmc — APPROVED** [review]
Could you add or augment an example showing use?

**Comment by nidzola** [comment]
> Could you add or augment an example showing use?

`TestBufferMemoryWithChatHistoryOption` is mimicking the store (that could be anything) and is an example of usage, do you think we need smth more?

**Comment by nidzola** [comment]
> @tmc Can we add `option.WithTokenLimit()` or something of the kind here? I know python lib has TokenBuffer class to flush to chat msgs that overflow the token size for a model. Not sure if we need an entirely new buffer for that, so we might consider it... cc @FluffyKebab
> 
> related to #125

@tmc @Struki84 added the token limit logic https://github.com/tmc/langchaingo/pull/217

**Pull request merged**
