### PR TITLE
vectorstores: add Milvus

### LINKED ISSUE #59: integrate with milvus for vector-store
https://github.com/milvus-io/milvus-sdk-go

### PR DESCRIPTION
**Pull request by pattonjp**
In quest to run langchaingo locally without network dependencies. I've added the milvus vector store and huggingface's text-embeddings-inference api client. 

### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [x] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

fixes #59

### CODE REVIEW

**Comment by tmc** [comment]
@pattonjp why close this?

**Comment by pattonjp** [comment]
created in this repo accidentally. will reopen as draft while testing.

**Comment by wangzhuzhen** [comment]
@pattonjp @tmc  How about this vectorstores Milvus？we need this 😄

**Review by tmc — APPROVED** [review]
Discussion happening on https://github.com/tmc/langchaingo/issues/369 but I don't want to hold this up. LGTM

**Comment by tmc** [comment]
@pattonjp can the text-embeddings-router go into the docker-compose config?

**Comment by tmc** [comment]
@pattonjp why not use ollama for embeddings?

**Comment by eliben** [comment]
Specifically, the `tei` provider has some additional options - but could these be passed to the underlying client directly, instead of to the embedder? The embedder then just wraps any client

**Comment by pattonjp** [comment]
sure will have pr today

**Pull request merged**
