### PR TITLE
docs: add pgvector page

### PR DESCRIPTION
**Pull request by elnoro**
A simple documentation page for pgvector integration, in response to [this request](https://github.com/tmc/langchaingo/pull/534#pullrequestreview-1834369765).

There is no "Integrations" page in the docs, so I put it under /data_connectons/vector_stores.

### CODE REVIEW

**Comment by elnoro** [comment]
I'm not really sure what's happening with the linter & tests - no *.go files were changed.

**Comment by tmc** [comment]
Thanks!

**Comment by tmc** [comment]
can you pull draft: true?

**Comment by tmc** [comment]
can you pull draft: true?

**Pull request merged**
